name: CI

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.cache/ms-playwright

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: 'Lint'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-and-cache
      - run: pnpm i
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run typecheck

  test:
    needs: lint
    name: 'Build&Test: ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-and-cache
      - uses: ./.github/actions/setup-playwright
      - run: pnpm i
      - name: Build
        run: pnpm run build
      - name: Test
        if: runner.os == 'Linux'
        run: pnpm run test:ci
      - name: Test (Light)
        if: runner.os != 'Linux'
        run: pnpm run test:ci --filter !@vitest/test-integration-dts-browser-playwright

  test-browser:
    needs: lint
    name: 'Browsers: ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-and-cache
      - uses: ./.github/actions/setup-playwright
      - run: pnpm i
      - run: pnpm run build
      - name: Test Browser
        if: runner.os != 'Windows'
        run: pnpm run test:browser:playwright
